on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to check if cats can be added to an array

    steps:
      - name: action step
        uses: jenbeltran/CICD-cats@v1.1

      - name: npm test
        run: npm test
