name: NodeJS CI

on: [push]

jobs:
  testing_cats_array:
    runs-on: ubuntu-latest
    name: A job to test mocha on cats array
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
